services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  resource-server:
    build:
      context: ./be-focus
      dockerfile: Dockerfile.java
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://your-database-host:5432/your-database-name
      - DATABASE_USERNAME=your-database-username
      - DATABASE_PASSWORD=your-database-password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - CLOUDINARY_CLOUD_NAME=your-cloudinary-cloud-name
      - CLOUDINARY_API_KEY=your-cloudinary-api-key
      - CLOUDINARY_API_SECRET=your-cloudinary-api-secret

volumes:
  redis-data:
